version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/rspamd"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/postfix"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/cortex_setup"
    schedule:
      interval: "daily"
