version: "3"

services:
  postfix_tx:
    image: peekabooav_postfix
    build: ./postfix
  cortex_setup:
    image: peekabooav_cortex_setup
    build: ./cortex_setup
  peekabooav:
    image: peekabooav
    build: ./
  rspamd:
    image: peekabooav_rspamd
    build: ./rspamd
  postfix_rx:
    image: peekabooav_postfix
    build: ./postfix
