version: "3"

services:
  postfix-tx:
    image: peekabooav-postfix
    build: ./postfix
  cortex-setup:
    image: peekabooav-cortex-setup
    build: ./cortex-setup
  peekabooav:
    image: peekabooav
    build: ./
  rspamd:
    image: peekabooav-rspamd
    build: ./rspamd
  postfix-rx:
    image: peekabooav-postfix
    build: ./postfix
