---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peekabooav.fullname" . }}
data:
  peekaboo.conf: |
    {{ include "peekabooav.config" .Values.config | b64enc }}
  analyzers.conf: |
    {{ include "peekabooav.config" .Values.analyzers | b64enc }}
  cortex-api-token: {{ .Values.cortex.apiToken | b64enc }}
  db-password: {{ .Values.db.password | b64enc }}
