apiVersion: v1
kind: Service
metadata:
  name: {{ include "peekabooav.fullname" . }}
  labels:
    {{- include "peekabooav.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8100
      protocol: TCP
      name: rest
  selector:
    {{- include "peekabooav.selectorLabels" . | nindent 4 }}
