apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cortex-setup.fullname" . }}
  labels:
    {{- include "cortex-setup.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cortex-setup.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cortex-setup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ELASTIC_URL
            value: {{ .Values.elasticsearch.url }}
          - name: CORTEX_URL
            value: {{ .Values.cortex.url | default (printf "http://%s-cortex:9001" .Release.Name) }}
          - name: PEEKABOO_CORTEX_API_TOKEN
            value: {{ required "Cortex apiToken must not be empty" .Values.cortex.apiToken }}
          - name: CORTEX_ADMIN_PASSWORD
            value: {{ required "Cortex adminPassword must not be empty" .Values.cortex.adminPassword }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
