apiVersion: v1
kind: Service
metadata:
  name: cortex
  namespace: peekabooav-pipeline
spec:
  selector:
    app: cortex
  sessionAffinity: None
  type: NodePort
  ports:
  - name: cortex
    port: 9001
    protocol: TCP
    targetPort: 9001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-jobs
  namespace: peekabooav-pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex
  namespace: peekabooav-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cortex
  namespace: peekabooav-pipeline
rules:
- apiGroups:
  - batch
  # wildcards don't work: https://github.com/kubernetes/kubernetes/issues/56582
  # A separate namespace is recommended which the cortex k8s runner doesn't
  # support, yet. So this is left insecure for now.
  #resourceNames:
  #- neuron-jobs-*
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cortex
  namespace: peekabooav-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cortex
subjects:
- kind: ServiceAccount
  name: cortex
  namespace: peekabooav-pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  namespace: peekabooav-pipeline
  labels:
    app: cortex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
      - name: cortex
        image: michaelweiser/cortex:3.1.4-1-k8s
        volumeMounts:
        - name: application
          mountPath: /etc/cortex/application.conf
          subPath: application.conf
        - name: analyzers
          mountPath: /etc/cortex/analyzers.json
          subPath: analyzers.json
        - mountPath: /tmp/cortex-jobs
          name: job-directory
        env:
        - name: CORTEX_ADMIN_PASSWORD
          value: dikka
        - name: analyzer_urls
          value: /etc/cortex/analyzers.json
        ports:
        - containerPort: 9001
          name: cortex
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: application
        configMap:
          name: cortex-application-conf
      - name: analyzers
        configMap:
          name: cortex-analyzers-json
      - name: job-directory
        persistentVolumeClaim:
          claimName: cortex-jobs
      serviceAccountName: cortex
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-application-conf
  namespace: peekabooav-pipeline
  selfLink: /api/v1/namespaces/peekabooav-pipeline/configmaps/cortex-application-conf
data:
  application.conf: |
    auth.method.basic=true
    job.kubernetes.persistentVolumeClaimName=cortex-jobs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-analyzers-json
  namespace: peekabooav-pipeline
  selfLink: /api/v1/namespaces/peekabooav-pipeline/configmaps/cortex-analyzers-json
data:
  analyzers.json: |
    [
      {
        "name": "FileInfo",
        "version": "8.0",
        "author": "TheHive-Project",
        "url": "https://github.com/TheHive-Project/Cortex-Analyzers",
        "license": "AGPL-V3",
        "description": "Parse files in several formats such as OLE and OpenXML to detect VBA macros, extract their source code, generate useful information on PE, PDF files...",
        "dataTypeList": ["file"],
        "baseConfig": "FileInfo",
        "configurationItems": [
          {
            "name": "manalyze_enable",
            "description": "Wether to enable manalyze submodule or not.",
            "type": "boolean",
            "required": true,
            "multi": false,
            "defaultValue": false
          },
          {
            "name": "manalyze_enable_docker",
            "description": "Use docker to run Manalyze. Can be used only if not using the docker image of FileInfo",
            "type": "boolean",
            "required": false,
            "multi": false,
            "defaultValue": false
          },
          {
            "name": "manalyze_enable_binary",
            "description": "Use local binary to run Manalyze. Need to compile it before!",
            "type": "boolean",
            "required": false,
            "multi": false,
            "defaultValue": true
          },
          {
            "name": "manalyze_binary_path",
            "description": "Path to the Manalyze binary that was compiled before. Keep the default value if using the docker image of FileInfo ",
            "type": "string",
            "required": false,
            "multi": false,
            "defaultValue": "/worker/Manalyze/bin/manalyze"
          },
          {
            "name": "floss_enable",
            "description": "Enable the use of FireEye FLARE FLOSS",
            "type": "boolean",
            "required": false,
            "multi": false,
            "default": false
          },
          {
            "name": "floss_binary_path",
            "description": "Path to the FLOSS binary.",
            "type": "string",
            "required": false,
            "multi": false,
            "default": "/usr/bin/floss"
          },
          {
            "name": "floss_minimal_string_length",
            "description": "Length of strings must be in order to be considered.",
            "type": "number",
            "required": false,
            "multi": false,
            "default": 4
          }
        ],
        "dockerImage": "cortexneurons/fileinfo:8"
      }
    ]
