apiVersion: v1
kind: Service
metadata:
  name: rspamd
  namespace: peekabooav-pipeline
spec:
  selector:
    app: rspamd
  sessionAffinity: None
  type: NodePort
  ports:
  - name: rspamd
    port: 11332
    protocol: TCP
    targetPort: 11332
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rspamd
  namespace: peekabooav-pipeline
  labels:
    app: rspamd
spec:
  replicas: 1
  selector:
      matchLabels:
        app: rspamd
  template:
    metadata:
      labels:
        app: rspamd
    spec:
      containers:
      - name: rspamd
        image: peekabooav_rspamd:local
      dnsPolicy: ClusterFirst
