apiVersion: v1
kind: Service
metadata:
  name: {{ include "rspamd.fullname" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11332
      protocol: TCP
      name: rspamd
  selector:
    {{- include "rspamd.selectorLabels" . | nindent 4 }}
